version: '3.8'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: mobiauto
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    networks:
      - mobiauto-network

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/mobiauto?authSource=admin
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - mobiauto-network
networks:
  mobiauto-network:
    driver: bridge
